// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(PlanetsDb))]
    [Migration("20230710174918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Planet", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<string>("Mass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SunDistance")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Name = "Mercury",
                            Diameter = 4879.3999999999996,
                            Mass = "3.285 × 10^23 kg",
                            Order = 1,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mercury_in_true_color.jpg/1024px-Mercury_in_true_color.jpg",
                            SunDistance = 52.585000000000001
                        },
                        new
                        {
                            Name = "Venus",
                            Diameter = 12104.0,
                            Mass = "4.867 × 10^24 kg",
                            Order = 2,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/b/b2/Venus_2_Approach_Image.jpg",
                            SunDistance = 108.73
                        },
                        new
                        {
                            Name = "Earth",
                            Diameter = 12742.0,
                            Mass = "5.972 × 10^24 kg",
                            Order = 3,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/The_Blue_Marble_%28remastered%29.jpg/1024px-The_Blue_Marble_%28remastered%29.jpg",
                            SunDistance = 152.09
                        },
                        new
                        {
                            Name = "Mars",
                            Diameter = 6779.0,
                            Mass = "6.39 × 10^23 kg",
                            Order = 4,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/0/0c/Mars_-_August_30_2021_-_Flickr_-_Kevin_M._Gill.png",
                            SunDistance = 249.47
                        },
                        new
                        {
                            Name = "Jupiter",
                            Diameter = 139820.0,
                            Mass = "1.898 × 10^27 kg",
                            Order = 5,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c1/Jupiter_New_Horizons.jpg",
                            SunDistance = 741.84000000000003
                        },
                        new
                        {
                            Name = "Saturn",
                            Diameter = 116460.0,
                            Mass = "5.683 × 10^26 kg",
                            Order = 6,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c7/Saturn_during_Equinox.jpg",
                            SunDistance = 1462.3
                        },
                        new
                        {
                            Name = "Uranus",
                            Diameter = 50724.0,
                            Mass = "8.681 × 10^25",
                            Order = 7,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c9/Uranus_as_seen_by_NASA%27s_Voyager_2_%28remastered%29_-_JPEG_converted.jpg",
                            SunDistance = 2937.0999999999999
                        },
                        new
                        {
                            Name = "Neptune",
                            Diameter = 49244.0,
                            Mass = "1.024 × 10^26",
                            Order = 8,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/6/63/Neptune_-_Voyager_2_%2829347980845%29_flatten_crop.jpg",
                            SunDistance = 4473.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
