// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(PlanetsDb))]
    partial class PlanetsDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Planet", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<string>("Mass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SunDistance")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Name = "Mercury",
                            Description = "Mercury—the smallest planet in our solar system and closest to the Sun—is only slightly larger than Earth's Moon. Mercury is the fastest planet, zipping around the Sun every 88 Earth days.",
                            Diameter = 4879.3999999999996,
                            Mass = "3.285 × 10^23 kg",
                            Order = 1,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mercury_in_true_color.jpg/1024px-Mercury_in_true_color.jpg",
                            SunDistance = 52.585000000000001
                        },
                        new
                        {
                            Name = "Venus",
                            Description = "Venus spins slowly in the opposite direction from most planets. A thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.",
                            Diameter = 12104.0,
                            Mass = "4.867 × 10^24 kg",
                            Order = 2,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/b/b2/Venus_2_Approach_Image.jpg",
                            SunDistance = 108.73
                        },
                        new
                        {
                            Name = "Earth",
                            Description = "Earth—our home planet—is the only place we know of so far that’s inhabited by living things. It's also the only planet in our solar system with liquid water on the surface.",
                            Diameter = 12742.0,
                            Mass = "5.972 × 10^24 kg",
                            Order = 3,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/The_Blue_Marble_%28remastered%29.jpg/1024px-The_Blue_Marble_%28remastered%29.jpg",
                            SunDistance = 152.09
                        },
                        new
                        {
                            Name = "Mars",
                            Description = "Mars is a dusty, cold, desert world with a very thin atmosphere. There is strong evidence Mars was – billions of years ago – wetter and warmer, with a thicker atmosphere.",
                            Diameter = 6779.0,
                            Mass = "6.39 × 10^23 kg",
                            Order = 4,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/0/0c/Mars_-_August_30_2021_-_Flickr_-_Kevin_M._Gill.png",
                            SunDistance = 249.47
                        },
                        new
                        {
                            Name = "Jupiter",
                            Description = "Jupiter is more than twice as massive than the other planets of our solar system combined. The giant planet's Great Red spot is a centuries-old storm bigger than Earth.",
                            Diameter = 139820.0,
                            Mass = "1.898 × 10^27 kg",
                            Order = 5,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c1/Jupiter_New_Horizons.jpg",
                            SunDistance = 741.84000000000003
                        },
                        new
                        {
                            Name = "Saturn",
                            Description = "Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as spectacular as Saturn's. ",
                            Diameter = 116460.0,
                            Mass = "5.683 × 10^26 kg",
                            Order = 6,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c7/Saturn_during_Equinox.jpg",
                            SunDistance = 1462.3
                        },
                        new
                        {
                            Name = "Uranus",
                            Description = "Uranus—seventh planet from the Sun—rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin on its side.",
                            Diameter = 50724.0,
                            Mass = "8.681 × 10^25",
                            Order = 7,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c9/Uranus_as_seen_by_NASA%27s_Voyager_2_%28remastered%29_-_JPEG_converted.jpg",
                            SunDistance = 2937.0999999999999
                        },
                        new
                        {
                            Name = "Neptune",
                            Description = "Neptune—the eighth and most distant major planet orbiting our Sun—is dark, cold and whipped by supersonic winds. It was the first planet located through mathematical calculations. ",
                            Diameter = 49244.0,
                            Mass = "1.024 × 10^26",
                            Order = 8,
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/6/63/Neptune_-_Voyager_2_%2829347980845%29_flatten_crop.jpg",
                            SunDistance = 4473.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
