version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: planets-db
    environment:
      - MSSQL_SA_PASSWORD=myStrongPassword
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"



